action_repeat: null
action_stat:
  0: 3514
  1: 3512
  2: 3294
agent_history_length: 4
cropx: null
cropy: null
discount_factor: 0.99
episode_counter: 51
episodes: 100000
epsilon: 0.09999999999985551
eval_episodes: 50
final_exploration: 0.1
final_exploration_frame: 10000
game_id: MountainCar-v0
initial_exploration: 1
input_imgx: 84
input_imgy: 84
learning_rate: 0.0001
minibatch_size: 32
random_seed: 1332
replay_memory_size: 10000
replay_start_size: 1000
target_network_update_frequency: 10000
time_steps: 200
total_steps_counter: 10320
train_steps_counter: 2376
update_frequency: 4
